<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Nosotros.aspx.cs" Inherits="Nosotros" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table style="width: 100%">
        <tr>
            <td align="center" bgcolor="White">
                <img alt="nosotros" src="images/demo/productos.png" style="width: 451px; height: 244px" /><br />
                <br />
                <p style="margin: 10px 0px; color: rgb(100, 101, 105); font-family: &quot;Electrolux Sans Regular&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 904px;">
                    <strong style="font-weight: bold; font-family: &quot;Electrolux Sans Semibold&quot;, sans-serif;">Electrolux es líder global en electrodomésticos y aparatos de uso profesional, vendiendo más de 40 millones de productos a clientes en más de 150 mercados cada año.</strong></p>
                <p style="margin: 10px 0px; color: rgb(100, 101, 105); font-family: &quot;Electrolux Sans Regular&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <p align="center" style="margin: 10px 0px; color: rgb(100, 101, 105); font-family: &quot;Electrolux Sans Regular&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 907px;">
                    La compañía se centra en las innovaciones que han sido cuidadosamente diseñadas, basadas &#8203;&#8203;en una visión amplia de los consumidores, para satisfacer las necesidades reales de los consumidores y profesionales. Los productos de Electrolux incluyen frigoríficos, lavavajillas, lavadoras, aspiradoras, hornos y aparatos de aire acondicionado, las cuales se venden bajo las marcas Electrolux, AEG, Eureka y Frigidaire. En 2011 tuvo una facturación de Electrolux SEK 102 mil millones y 58.000 empleados.</p>
                <p align="center" style="margin: 10px 0px; color: rgb(100, 101, 105); font-family: &quot;Electrolux Sans Regular&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 909px;">
                    <strong style="font-weight: bold; font-family: &quot;Electrolux Sans Semibold&quot;, sans-serif;">90 AÑOS DE INNOVACIONES LÍDERES Y DISEÑO</strong><span>&nbsp;</span>Axel Wenner-Gren, el padre fundador de Electrolux, estableció los principios por los que la compañía todavía prospera. Su sueño de mejorar la calidad de vida ha tenido un impacto fundamental en los hogares de todo el mundo. Electrolux hoy, 90 años después, es un líder global en electrodomésticos y aparatos de uso profesional. &quot;Pensando en ti&quot; expresa la oferta de Electrolux: Mantener enfoque continuo en el consumidor, se trata de una cuestión de desarrollo de productos, diseño, producción, comercialización, logística o servicio.</p>
                <p style="margin: 10px 0px; color: rgb(100, 101, 105); font-family: &quot;Electrolux Sans Regular&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 906px;">
                    <strong style="font-weight: bold; font-family: &quot;Electrolux Sans Semibold&quot;, sans-serif;">Electrolux en Argentina</strong></p>
                <p align="center" style="margin: 10px 0px; color: rgb(100, 101, 105); font-family: &quot;Electrolux Sans Regular&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 907px;">
                    Lleva más de 70 años en el mercado. Anteriormente, los productos llegaban a los hogares con venta directa y hoy en día Electrolux, vende a través de una granred de distribución. Almacenes Tradicionales, Almacenes, Especializados, Mayoristas, Hipermercados, Contamos con una amplia gama de productos: aspiradoras, brilladoras, pequeños electrodomésticos, neveras, nevecones, lavadoras, secadoras, aires acondicionados, torres, microondas, estufas, campanas, congeladoras, entre otros. </p>
        </tr>
    </table>
</asp:Content>

